// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqptxUOVU6sIJBcXWsnmGn4u9_jjGrCNo',
    appId: '1:1050344469051:web:660ef64fdfb9de6f26a21e',
    messagingSenderId: '1050344469051',
    projectId: 'flutter-test-bug',
    authDomain: 'flutter-test-bug.firebaseapp.com',
    storageBucket: 'flutter-test-bug.appspot.com',
    measurementId: 'G-831E34RK8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY28U3sjA_QpBX1p9khTrIwIu9R6Jabag',
    appId: '1:1050344469051:android:75a9bbbda2eb617926a21e',
    messagingSenderId: '1050344469051',
    projectId: 'flutter-test-bug',
    storageBucket: 'flutter-test-bug.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7r2XTfi4PAnekOdjG-LvKU8ylcW5F7wE',
    appId: '1:1050344469051:ios:ddae7dbb6b2ac01f26a21e',
    messagingSenderId: '1050344469051',
    projectId: 'flutter-test-bug',
    storageBucket: 'flutter-test-bug.appspot.com',
    iosBundleId: 'com.example.firebaseAnalyHehe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7r2XTfi4PAnekOdjG-LvKU8ylcW5F7wE',
    appId: '1:1050344469051:ios:acdb37a61e69fac226a21e',
    messagingSenderId: '1050344469051',
    projectId: 'flutter-test-bug',
    storageBucket: 'flutter-test-bug.appspot.com',
    iosBundleId: 'com.example.firebaseAnalyHehe.RunnerTests',
  );
}
